#include "oled_anim.h"
#include "driver/i2c.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <stdio.h>

// === I2C CONFIG ===
#define I2C_MASTER_SCL_IO           22
#define I2C_MASTER_SDA_IO           21
#define I2C_MASTER_NUM              I2C_NUM_0
#define I2C_MASTER_FREQ_HZ          400000
#define I2C_MASTER_TX_BUF_DISABLE   0
#define I2C_MASTER_RX_BUF_DISABLE   0

#define OLED_ADDR 0x3C

// === Frames ===
#include "frames.c"  // generated by Python GIF converter

// === Low-level I2C helpers ===
static esp_err_t ssd1306_cmd(uint8_t cmd) {
    i2c_cmd_handle_t handle = i2c_cmd_link_create();
    i2c_master_start(handle);
    i2c_master_write_byte(handle, (OLED_ADDR << 1) | I2C_MASTER_WRITE, true);
    i2c_master_write_byte(handle, 0x00, true); // command
    i2c_master_write_byte(handle, cmd, true);
    i2c_master_stop(handle);
    esp_err_t ret = i2c_master_cmd_begin(I2C_MASTER_NUM, handle, pdMS_TO_TICKS(100));
    i2c_cmd_link_delete(handle);
    return ret;
}

static esp_err_t ssd1306_data(const uint8_t *data, size_t len) {
    i2c_cmd_handle_t handle = i2c_cmd_link_create();
    i2c_master_start(handle);
    i2c_master_write_byte(handle, (OLED_ADDR << 1) | I2C_MASTER_WRITE, true);
    i2c_master_write_byte(handle, 0x40, true); // data
    i2c_master_write(handle, data, len, true);
    i2c_master_stop(handle);
    esp_err_t ret = i2c_master_cmd_begin(I2C_MASTER_NUM, handle, pdMS_TO_TICKS(100));
    i2c_cmd_link_delete(handle);
    return ret;
}

// === SSD1306 initialization ===
static void ssd1306_init_hw(void) {
    ssd1306_cmd(0xAE);         // Display off
    ssd1306_cmd(0xD5); ssd1306_cmd(0xA0); // Set display clock
    ssd1306_cmd(0xA8); ssd1306_cmd(0x3F); // Multiplex ratio 1/64
    ssd1306_cmd(0xD3); ssd1306_cmd(0x00); // Display offset
    ssd1306_cmd(0x40);         // Display start line
    ssd1306_cmd(0xA1);         // Segment remap
    ssd1306_cmd(0xC8);         // COM scan direction remap
    ssd1306_cmd(0xDA); ssd1306_cmd(0x12); // COM pins hardware config
    ssd1306_cmd(0x81); ssd1306_cmd(0x7F); // Contrast
    ssd1306_cmd(0xA4);         // Resume to RAM content
    ssd1306_cmd(0xA6);         // Normal display (not inverted)
    ssd1306_cmd(0xD9); ssd1306_cmd(0x22); // Pre-charge
    ssd1306_cmd(0xDB); ssd1306_cmd(0x20); // VCOM deselect level
    // ⚠️ SSD1309 usually doesn’t have charge pump enable (0x8D), skip that
    ssd1306_cmd(0xAF);         // Display on
}

// === Clear screen ===
void ssd1306_clear(void) {
    uint8_t buffer[128] = {0};
    for (int page = 0; page < 8; page++) {
        ssd1306_cmd(0xB0 + page);
        ssd1306_cmd(0x00);
        ssd1306_cmd(0x10);
        ssd1306_data(buffer, 128);
    }
}

// === Draw one frame ===
static void ssd1306_draw_frame(const uint8_t *frame) {
    for (int page = 0; page < 8; page++) {
        ssd1306_cmd(0xB0 + page);
        ssd1306_cmd(0x00);
        ssd1306_cmd(0x10);
        ssd1306_data(&frame[page * 128], 128);
    }
}

// === Public functions ===
void oled_anim_init(void) {
    // I2C master init
    i2c_config_t conf = {
        .mode = I2C_MODE_MASTER,
        .sda_io_num = I2C_MASTER_SDA_IO,
        .scl_io_num = I2C_MASTER_SCL_IO,
        .sda_pullup_en = GPIO_PULLUP_ENABLE,
        .scl_pullup_en = GPIO_PULLUP_ENABLE,
        .master.clk_speed = I2C_MASTER_FREQ_HZ,
    };
    i2c_param_config(I2C_MASTER_NUM, &conf);
    i2c_driver_install(I2C_MASTER_NUM, conf.mode,
                       I2C_MASTER_RX_BUF_DISABLE,
                       I2C_MASTER_TX_BUF_DISABLE, 0);

    ssd1306_init_hw();
    ssd1306_clear();
}

void oled_anim_play(int delay_ms) {
    for (int i = 0; i < animation_frame_count; i++) {
        ssd1306_draw_frame(animation_frames[i]);
        vTaskDelay(pdMS_TO_TICKS(delay_ms));
    }
}
